const { withGradleProperties } = require('expo/config-plugins');

/**
 * Build native code for arm64-v8a alone.
 *
 * The default builds four architectures — `armeabi-v7a,arm64-v8a,x86,x86_64` —
 * and every one of them compiles the full NDK tree. Measured here: a clean
 * release build spent over ten minutes in the C++ stage and produced a 107 MB
 * APK, against roughly 45 MB and a quarter of the time for arm64 alone.
 *
 * Every phone this app is built for is arm64. `x86`/`x86_64` exist for
 * emulators, and `armeabi-v7a` for 32-bit devices that have not shipped in
 * years. If an emulator is ever needed, override it for that build rather than
 * paying for it on every one:
 *
 *     ./gradlew assembleRelease -PreactNativeArchitectures=x86_64
 *
 * A plugin rather than an edit to `android/gradle.properties`, because that file
 * is regenerated by `expo prebuild` and the setting would silently revert — which
 * is this project's most expensive recurring class of bug.
 */
module.exports = function withArm64Only(config) {
  return withGradleProperties(config, (cfg) => {
    const props = cfg.modResults.filter(
      (p) => !(p.type === 'property' && p.key === 'reactNativeArchitectures')
    );
    props.push({ type: 'property', key: 'reactNativeArchitectures', value: 'arm64-v8a' });
    cfg.modResults = props;
    return cfg;
  });
};
